In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv("weather_data.csv")

In [3]:
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [4]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [5]:
df.shape

(8784, 8)

In [6]:
df.index

RangeIndex(start=0, stop=8784, step=1)

In [7]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='str')

### RENAMED COLUMNS

In [8]:
df = df.rename(columns = {"Date/Time" : "DateTime", 'Temp_C': "Temperature",  'Dew Point Temp_C': "DewPoint", 'Rel Hum_%': "RelativeHumidity",
       'Wind Speed_km/h': "WindSpeed", 'Visibility_km': "Visibility", 'Press_kPa': "Pressure", 'Weather': "Weather"})

In [9]:
df.dtypes

DateTime                str
Temperature         float64
DewPoint            float64
RelativeHumidity      int64
WindSpeed             int64
Visibility          float64
Pressure            float64
Weather                 str
dtype: object

In [10]:
df['Weather'].unique()

<StringArray>
[                                    'Fog',
                    'Freezing Drizzle,Fog',
                           'Mostly Cloudy',
                                  'Cloudy',
                                    'Rain',
                            'Rain Showers',
                            'Mainly Clear',
                            'Snow Showers',
                                    'Snow',
                                   'Clear',
                       'Freezing Rain,Fog',
                           'Freezing Rain',
                        'Freezing Drizzle',
                               'Rain,Snow',
                           'Moderate Snow',
                   'Freezing Drizzle,Snow',
               'Freezing Rain,Snow Grains',
                       'Snow,Blowing Snow',
                            'Freezing Fog',
                                    'Haze',
                                'Rain,Fog',
                             'Drizzle,Fog',
                                 'Drizzle',
                   'Freezing Drizzle,Haze',
                      'Freezing Rain,Haze',
                               'Snow,Haze',
                                'Snow,Fog',
                        'Snow,Ice Pellets',
                               'Rain,Haze',
                      'Thunderstorms,Rain',
              'Thunderstorms,Rain Showers',
        'Thunderstorms,Heavy Rain Showers',
          'Thunderstorms,Rain Showers,Fog',
                           'Thunderstorms',
                  'Thunderstorms,Rain,Fog',
 'Thunderstorms,Moderate Rain Showers,Fog',
                        'Rain Showers,Fog',
               'Rain Showers,Snow Showers',
                            'Snow Pellets',
                           'Rain,Snow,Fog',
                       'Moderate Rain,Fog',
           'Freezing Rain,Ice Pellets,Fog',
                 'Drizzle,Ice Pellets,Fog',
                            'Drizzle,Snow',
                        'Rain,Ice Pellets',
                        'Drizzle,Snow,Fog',
                        'Rain,Snow Grains',
                   'Rain,Snow,Ice Pellets',
                        'Snow Showers,Fog',
              'Moderate Snow,Blowing Snow']
Length: 50, dtype: str

In [11]:
df.nunique()

DateTime            8784
Temperature          533
DewPoint             489
RelativeHumidity      83
WindSpeed             34
Visibility            24
Pressure             518
Weather               50
dtype: int64

In [12]:
df.count()

DateTime            8784
Temperature         8784
DewPoint            8784
RelativeHumidity    8784
WindSpeed           8784
Visibility          8784
Pressure            8784
Weather             8784
dtype: int64

In [13]:
df.Weather.value_counts().head(10)

Weather
Mainly Clear     2106
Mostly Cloudy    2069
Cloudy           1728
Clear            1326
Snow              390
Rain              306
Rain Showers      188
Fog               150
Rain,Fog          116
Drizzle,Fog        80
Name: count, dtype: int64

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DateTime          8784 non-null   str
 1   Temperature       8784 non-null   float64
 2   DewPoint          8784 non-null   float64
 3   RelativeHumidity  8784 non-null   int64
 4   WindSpeed         8784 non-null   int64
 5   Visibility        8784 non-null   float64
 6   Pressure          8784 non-null   float64
 7   Weather           8784 non-null   str
dtypes: float64(4), int64(2), str(2)
memory usage: 549.1 KB

### Wind Speed Unique Values

In [16]:
df.WindSpeed.nunique()

34

In [19]:
df.WindSpeed.sort_values(ascending = True).unique()

array([ 0,  2,  4,  6,  7,  9, 11, 13, 15, 17, 19, 20, 22, 24, 26, 28, 30,
       32, 33, 35, 37, 39, 41, 43, 44, 46, 48, 50, 52, 54, 57, 63, 70, 83])

### No. of times when the "Weather is exactly Clear"

In [22]:
df.Weather.value_counts().head(10)

Weather
Mainly Clear     2106
Mostly Cloudy    2069
Cloudy           1728
Clear            1326
Snow              390
Rain              306
Rain Showers      188
Fog               150
Rain,Fog          116
Drizzle,Fog        80
Name: count, dtype: int64

In [23]:
df[df['Weather'] == 'Clear']

,DateTime,Temperature,DewPoint,RelativeHumidity,WindSpeed,Visibility,Pressure,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [24]:
df.groupby('Weather').get_group("Clear")

,DateTime,Temperature,DewPoint,RelativeHumidity,WindSpeed,Visibility,Pressure,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear